language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - dist/functions/node_modules
install:
  - npm install
script:
  - npm run build
  - npm run funcs:predeploy
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
