language: node_js
node_js:
  - "stable"
env:
  global:
    - NODE_ENV=development
cache:
  directories:
    - node_modules
script:
  - npm run build
after_success:
  - npm run funcs:predeploy
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
